"""
=============================================================
  STEP 2: MODEL TRAINING
  File: backend/model/train.py
=============================================================

PURPOSE:
    Train a text classification model to detect sentiment
    (positive / negative / neutral) in social media posts.

ML PIPELINE OVERVIEW:
    Raw Text
      ↓  [Text Cleaning]
    Cleaned Text
      ↓  [TF-IDF Vectorization]
    Numerical Feature Matrix
      ↓  [Logistic Regression]
    Predicted Sentiment Label

WHY THESE CHOICES?
    - TF-IDF: Simple, fast, interpretable. Great starting point
              for text classification before jumping to deep learning.
    - Logistic Regression: Simple, fast, interpretable.
              Excellent baseline for multi-class text classification.
              Easy to understand and explain in interviews.

CONCEPTS COVERED:
    - Text preprocessing / cleaning
    - TF-IDF feature extraction
    - Train/Test split
    - Model evaluation (accuracy, precision, recall, F1)
    - Model persistence with pickle

RUN AFTER generate_data.py:
    python train.py
"""

# ─────────────────────────────────────────────
#   IMPORTS
# ─────────────────────────────────────────────

import os           # File path management
import re           # Regular expressions for text cleaning
import pickle       # Saving/loading the trained model
import csv          # Reading our generated dataset

# scikit-learn: The industry-standard ML library for Python
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
)
from sklearn.pipeline import Pipeline  # Chain steps into one object


# ─────────────────────────────────────────────
#   CONFIGURATION
#   Centralizing config makes it easy to tune
#   hyperparameters without hunting through code.
# ─────────────────────────────────────────────

CONFIG = {
    # Fraction of data reserved for testing (not seen during training)
    # 0.2 = 80% train, 20% test — common industry split
    "test_size": 0.2,

    # Seed for reproducibility — same split every time
    "random_state": 42,

    # TF-IDF settings
    "tfidf_max_features": 5000,   # Keep only top N words by frequency
    "tfidf_ngram_range": (1, 2),  # Unigrams + bigrams ("not good" matters!)

    # Logistic Regression settings
    "lr_max_iter": 1000,          # Max iterations for solver to converge
    "lr_C": 1.0,                  # Regularization strength (smaller = stronger)
}


# ─────────────────────────────────────────────
#   STEP A: TEXT CLEANING
# ─────────────────────────────────────────────

def clean_text(text: str) -> str:
    """
    Normalize raw social media text for ML processing.

    Social media text is messy:
        - URLs add noise (https://t.co/xyz → not useful)
        - @mentions identify users, not sentiment
        - Repeated characters ("sooooo good") reduce vocabulary diversity
        - Extra whitespace causes inconsistency

    We keep:
        - Words (letters, numbers)
        - Emojis and punctuation that carry sentiment
          (We simplify by keeping only alphanum + spaces here;
           in a production system you'd use emoji libraries)

    Args:
        text: Raw input string
    Returns:
        Cleaned, lowercased string
    """

    # 1. Lowercase everything for consistency
    #    "GREAT" and "great" should be treated identically
    text = text.lower()

    # 2. Remove URLs (http/https links)
    #    Regex: r'http\S+' matches "http" followed by any non-space characters
    text = re.sub(r"http\S+", "", text)

    # 3. Remove @mentions (e.g., @username)
    text = re.sub(r"@\w+", "", text)

    # 4. Remove hashtag symbols but keep the word
    #    "#happy" → "happy"  (the word itself carries sentiment)
    text = re.sub(r"#", "", text)

    # 5. Remove characters that aren't letters, numbers, or spaces
    #    This strips special characters and stray punctuation
    text = re.sub(r"[^a-z0-9\s]", "", text)

    # 6. Collapse multiple spaces into one
    text = re.sub(r"\s+", " ", text).strip()

    return text


# ─────────────────────────────────────────────
#   STEP B: LOAD DATASET
# ─────────────────────────────────────────────

def load_dataset(csv_path: str):
    """
    Read the CSV file and return parallel lists of texts and labels.

    Args:
        csv_path: Path to the CSV generated by generate_data.py
    Returns:
        texts  : List of raw post strings
        labels : List of sentiment strings ('positive'/'negative'/'neutral')
    """

    texts  = []
    labels = []

    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)  # Reads each row as a dict using header names
        for row in reader:
            texts.append(row["text"])
            labels.append(row["sentiment"])

    print(f"  ✔ Loaded {len(texts)} samples from {csv_path}")
    return texts, labels


# ─────────────────────────────────────────────
#   STEP C: TRAIN THE MODEL
# ─────────────────────────────────────────────

def train(csv_path: str, model_output_path: str) -> None:
    """
    Full training pipeline: load → clean → vectorize → train → evaluate → save.

    Args:
        csv_path          : Path to training CSV
        model_output_path : Where to save the trained pipeline (.pkl)
    """

    print("\n" + "=" * 55)
    print("  TRAINING SENTIMENT ANALYSIS MODEL")
    print("=" * 55)

    # ── B: Load raw data ──
    print("\n[1/5] Loading dataset...")
    texts, labels = load_dataset(csv_path)

    # ── A: Clean all texts ──
    print("[2/5] Cleaning text...")
    texts_clean = [clean_text(t) for t in texts]

    # ── C: Split into training and testing sets ──
    # WHY SPLIT?
    #   We need unseen data to honestly evaluate performance.
    #   If we test on training data, the model just "memorizes" answers.
    print("[3/5] Splitting data...")
    X_train, X_test, y_train, y_test = train_test_split(
        texts_clean,
        labels,
        test_size=CONFIG["test_size"],
        random_state=CONFIG["random_state"],
        stratify=labels,  # Ensure each split has equal class proportions
    )
    print(f"       Train size : {len(X_train)}")
    print(f"       Test size  : {len(X_test)}")

    # ── D: Build the ML Pipeline ──
    # A Pipeline chains preprocessing + model into a single object.
    # This is CRITICAL for deployment: you call pipeline.predict(raw_text)
    # and it automatically cleans + vectorizes before predicting.
    print("[4/5] Building and training pipeline...")

    pipeline = Pipeline([

        # STEP 1 — TF-IDF Vectorizer
        # Converts text strings → numerical feature matrix
        #
        # TF-IDF = Term Frequency × Inverse Document Frequency
        #   TF   : How often does a word appear in THIS document?
        #   IDF  : How rare is this word across ALL documents?
        #   High TF-IDF → Word is frequent here but rare elsewhere → distinctive!
        #
        # ngram_range=(1,2) captures:
        #   Unigrams: ["not", "good"] — individual words
        #   Bigrams : ["not good"]    — word pairs (important for negation!)
        ("tfidf", TfidfVectorizer(
            max_features=CONFIG["tfidf_max_features"],
            ngram_range=CONFIG["tfidf_ngram_range"],
            stop_words="english",   # Remove common words: "the", "is", "and"...
            min_df=2,               # Ignore words appearing in fewer than 2 docs
        )),

        # STEP 2 — Logistic Regression Classifier
        # Despite the name, this is a CLASSIFICATION algorithm.
        # It learns the probability of each class given the TF-IDF features.
        #
        # multi_class='multinomial': Handles 3+ classes natively
        # C=1.0: Regularization parameter (prevents overfitting)
        ("classifier", LogisticRegression(
            
            max_iter=CONFIG["lr_max_iter"],
            C=CONFIG["lr_C"],
            random_state=CONFIG["random_state"],
        )),
    ])

    # FIT: The model learns from training data
    pipeline.fit(X_train, y_train)
    print("       ✔ Training complete!")

    # ── E: Evaluate on the test set ──
    print("\n[5/5] Evaluating model on test set...")
    y_pred = pipeline.predict(X_test)

    # Accuracy: percentage of correct predictions
    accuracy = accuracy_score(y_test, y_pred)

    # Classification Report: Precision, Recall, F1-Score per class
    #   Precision = Of all predicted positives, how many were actually positive?
    #   Recall    = Of all actual positives, how many did we predict correctly?
    #   F1-Score  = Harmonic mean of Precision & Recall (balanced metric)
    report = classification_report(y_test, y_pred,
                                   target_names=["negative", "neutral", "positive"])

    # Confusion Matrix: Shows where the model makes mistakes
    cm = confusion_matrix(y_test, y_pred,
                          labels=["negative", "neutral", "positive"])

    print(f"\n  📊 ACCURACY: {accuracy:.4f} ({accuracy*100:.2f}%)")
    print("\n  📋 CLASSIFICATION REPORT:")
    print(report)
    print("  🔢 CONFUSION MATRIX (rows=actual, cols=predicted):")
    print("     Labels: [negative, neutral, positive]")
    for row in cm:
        print("    ", row.tolist())

    # ── F: Save the trained pipeline ──
    # pickle serializes Python objects to bytes → saves to disk
    # We save the ENTIRE pipeline (vectorizer + model together)
    # so prediction only needs to call pipeline.predict()
    os.makedirs(os.path.dirname(model_output_path), exist_ok=True)
    with open(model_output_path, "wb") as f:  # "wb" = write binary
        pickle.dump(pipeline, f)

    print(f"\n  ✅ Model saved → {model_output_path}")
    print("=" * 55)


# ─────────────────────────────────────────────
#   ENTRY POINT
# ─────────────────────────────────────────────

if __name__ == "__main__":

    # Resolve paths relative to project structure
    script_dir  = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)  # Go up one level to backend/

    csv_path    = os.path.join(project_dir, "data", "social_media_data.csv")
    model_path  = os.path.join(script_dir, "sentiment_model.pkl")

    train(csv_path=csv_path, model_output_path=model_path)